apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: cookbookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.4.0
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_SERVER_ROOT_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: GF_SERVER_ROOT_URL
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-data
