version: '3.9'

services:
  traefik:
    image: traefik:v3.6.10
    container_name: traefik
    command:
      - '--configFile=/app/configs/traefik.toml'
    volumes:
      - ./apps/traefik/traefik.toml:/app/configs/traefik.toml:ro
      - ./apps/traefik/dynamic_conf.toml:/app/configs/dynamic_conf.toml:ro
      - ./apps/traefik/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.localhost`)'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls=true'
      - 'traefik.http.routers.traefik.service=api@internal'
    environment:
      - TZ=Europe/Helsinki
    ports:
      - '80:80'
      - '443:443'
    networks:
      - cookbookapp

  web:
    build:
      context: .
      dockerfile: apps/docker/Dockerfile.web
    container_name: web
    ports:
      - '${WEB_PORT}:3000'
    depends_on:
      - auth
    environment:
      AUTH_SERVICE_URL: http://auth:${AUTH_SERVICE_PORT}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web.rule=Host(`web.localhost`)'
      - 'traefik.http.routers.web.entrypoints=websecure'
      - 'traefik.http.routers.web.tls=true'
      - 'traefik.http.services.web.loadbalancer.server.port=3000'
    networks:
      - cookbookapp

  auth:
    build:
      context: .
      dockerfile: apps/docker/Dockerfile.auth
    container_name: auth-service
    ports:
      - '${AUTH_SERVICE_PORT}:4000'
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_DB_HOST: auth-db
      AUTH_DB_PORT: ${AUTH_DB_PORT}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.auth.rule=Host(`auth.localhost`)'
      - 'traefik.http.routers.auth.entrypoints=websecure'
      - 'traefik.http.routers.auth.tls=true'
      - 'traefik.http.services.auth.loadbalancer.server.port=4000'
    networks:
      - cookbookapp

  auth-db:
    image: mariadb:11
    container_name: auth-db
    restart: always
    environment:
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MYSQL_USER: ${AUTH_DB_USER}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
    ports:
      - '${AUTH_DB_PORT}:3306'
    volumes:
      - auth-db-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mariadb-admin', '--protocol=tcp', 'ping']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - cookbookapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '6060:80'
    environment:
      PMA_HOST: auth-db
      PMA_PORT: ${AUTH_DB_PORT}
      PMA_USER: ${AUTH_DB_USER}
      PMA_PASSWORD: ${AUTH_DB_PASSWORD}
    depends_on:
      - auth-db
    volumes:
      - phpmyadmin-data:/etc/phpmyadmin
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)'
      - 'traefik.http.routers.phpmyadmin.entrypoints=websecure'
      - 'traefik.http.routers.phpmyadmin.tls=true'
      - 'traefik.http.services.phpmyadmin.loadbalancer.server.port=80'
    networks:
      - cookbookapp

  recipe-management-service:
    build:
      context: .
      dockerfile: apps/docker/Dockerfile.recipe-management-service
    container_name: recipe-management-service
    ports:
      - '${RECIPE_MANAGEMENT_SERVICE_PORT}:5001'
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      RECIPE_MANAGEMENT_SERVICE_PORT: '5001'
      RECIPE_DB_NAME: ${RECIPE_DB_NAME}
      RECIPE_DB_USER: ${RECIPE_DB_USER}
      RECIPE_DB_PASSWORD: ${RECIPE_DB_PASSWORD}
      RECIPE_DB_HOST: user-db
      RECIPE_DB_PORT: '5432'

  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_DB: ${RECIPE_DB_NAME}
      POSTGRES_USER: ${RECIPE_DB_USER}
      POSTGRES_PASSWORD: ${RECIPE_DB_PASSWORD}
    ports:
      - '${RECIPE_DB_PORT}:5432'
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - user-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)'
      - 'traefik.http.routers.pgadmin.entrypoints=websecure'
      - 'traefik.http.routers.pgadmin.tls=true'
      - 'traefik.http.services.pgadmin.loadbalancer.server.port=80'
    networks:
      - cookbookapp

volumes:
  auth-db-data:
  phpmyadmin-data:
  user-db-data:
  pgadmin-data:

networks:
  cookbookapp:
    name: cookbookapp
    driver: bridge
