import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/providers/tanstack-provider';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'CookBookApp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {' '}
          <Toaster richColors closeButton />
          <main className="min-h-screen w-screen bg-neutral bg-linear-to-tl from-neutral to-tertiary flex items-top justify-center">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
