apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: cookbookapp
type: Opaque
stringData:
  JWT_SECRET: "${AUTH_JWT_SECRET}"
  AUTH_DB_NAME: "authdb"
  AUTH_DB_USER: "authuser"
  AUTH_DB_PASSWORD: "${AUTH_DB_PASSWORD}"
  AUTH_DB_ROOT_PASSWORD: "${AUTH_DB_ROOT_PASSWORD}"
