apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: cookbookapp
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME"
  AUTH_DB_NAME: "authdb"
  AUTH_DB_USER: "authuser"
  AUTH_DB_PASSWORD: "CHANGE_ME"
  AUTH_DB_ROOT_PASSWORD: "CHANGE_ME"
