apiVersion: v1
kind: Secret
metadata:
  name: recipe-secrets
  namespace: cookbookapp
type: Opaque
stringData:
  RECIPE_DB_NAME: "recipedb"
  RECIPE_DB_USER: "recipeuser"
  RECIPE_DB_PASSWORD: "CHANGE_ME"
