apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: cookbookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: web
          image: walaska/cookbookapp:web
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: RECIPE_SERVICE_URL
              value: "https://cookbook.fi/api/recipes"
            - name: AUTH_SERVICE_URL
              value: "https://cookbook.fi/api/auth"
