apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: cookbookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: walaska/cookbookapp:web
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: AUTH_SERVICE_URL
              value: http://auth:4000/api/auth
            - name: NEXT_PUBLIC_RECIPE_SERVICE_URL
              value: http://recipe-management:5001/api/recipes
