apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: cookbookapp
type: Opaque
stringData:
  NEXT_PUBLIC_RECIPE_SERVICE_URL: "${RECIPE_SERVICE_URL}"
  NEXT_PUBLIC_AUTH_SERVICE_URL: "${AUTH_SERVICE_URL}"
