apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: cookbookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: recommendation
          image: walaska/cookbookapp:recommendation
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET