# docker/Dockerfile.web

FROM node:20-alpine AS deps
WORKDIR /apps

COPY apps/web/package*.json ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /apps

ARG RECIPE_API_URL
ARG AUTH_API_URL
ENV RECIPE_API_URL=$RECIPE_API_URL
ENV AUTH_API_URL=$AUTH_API_URL

COPY --from=deps /apps/node_modules ./node_modules
COPY apps/web/ .

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /apps

ENV NODE_ENV=production

COPY --from=builder /apps ./

EXPOSE 3000

CMD ["npm", "start"]