FROM node:20-alpine

WORKDIR /app

COPY apps/recipe-management-service/package*.json ./

RUN npm ci

COPY apps/recipe-management-service/ .

RUN npm run build

EXPOSE 5001

CMD ["npm", "run", "start"]
